name: navhost_state_example
description: Example app for the navhost_state package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  navhost_state:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
